#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xd8,0x18,0xf9,0x56,0x27,0x0e,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0xd8,0x18,0xf9,0x56,0x4e,0x1e,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
